<a href="https://colab.research.google.com/github/ankitdhakal1010/Math/blob/main/Workshop_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ankit Dhakal
2607659

In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)
print(arr.flags)

int64
2
(3, 3)
9
8
72
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print the matrix.

In [6]:
arr = 3 * np.ones((4,5), dtype= float)
print(arr)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


What is the other way to create the same matrix as above?

In [7]:
arr = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2,(3,3), dtype= int)
print(arr)

[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]


Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4].

In [8]:
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain a matrix of shape (3,3) that contains only upper-left portion of the original matrix.

In [9]:
arr = np.fromfunction(lambda i, j: np.abs(i+1+j),(4,4),dtype= int)
print(arr)
print(arr[0:3, 0:3])

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


Part problem

There is an error as the dimention of the matrices doesn't have the same dimension

In [10]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,1,1],[2,2,2]])

print(A+B)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

Given a matrix and a vector, write a Python function that performs Matrix-Vector product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix- Matrix product

Given two compatible matrices, write a Python function that performs Matrix-Matrix product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix- Matrix product.

In [11]:
B = np.array([[5,6],[7,8]])

result = [[0,0],[0,0]]

for i in range(2):
    for j in range(2):
        for k in range(2):
            result[i][j] += A[i][k] * B[k][j]

print(result)

[[np.int64(19), np.int64(22)], [np.int64(55), np.int64(64)]]


Given a matrix, write a Python function that checks if it is a symmetric matrix.

In [12]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A2 = A.T

if (np.array_equal(A,A2)):
    print("Symetrical")

B= np.zeros((3,3))
B2 = B.T

if (np.array_equal(B,B2)):
    print("Symetrical")


Symetrical
